In [1]:
import torch
sample_points = 36
n_strips = 72
n_offsets = 72
sample_x_indexs=(torch.linspace(
            0, 1, steps=sample_points, dtype=torch.float32) *
                                n_strips).long()
print(sample_x_indexs)

prior_feat_ys=torch.flip(
            (1 - sample_x_indexs.float() / n_strips), dims=[-1])
print(prior_feat_ys.shape)
print(prior_feat_ys)

prior_ys =torch.linspace(1, 0,steps=n_offsets,dtype=torch.float32)
print(prior_ys)


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 72])
torch.Size([36])
tensor([0.0000, 0.0417, 0.0694, 0.0972, 0.1250, 0.1528, 0.1806, 0.2083, 0.2361,
        0.2639, 0.2917, 0.3194, 0.3472, 0.3750, 0.4028, 0.4306, 0.4583, 0.4861,
        0.5278, 0.5556, 0.5833, 0.6111, 0.6389, 0.6667, 0.6944, 0.7222, 0.7500,
        0.7778, 0.8056, 0.8333, 0.8611, 0.8889, 0.9167, 0.9444, 0.9722, 1.0000])
tensor([1.0000, 0.9859, 0.9718, 0.9577, 0.9437, 0.9296, 0.9155, 0.9014, 0.8873,
        0.8732, 0.8592, 0.8451, 0.8310, 0.8169, 0.8028, 0.7887, 0.7746, 0.7606,
        0.7465, 0.7324, 0.7183, 0.7042, 0.6901, 0.6761, 0.6620, 0.6479, 0.6338,
        0.6197, 0.6056, 0.5915, 0.5775, 0.5634, 0.5493, 0.5352, 0.5211, 0.5070,
        0.4930, 0.4789, 0.4648, 0.4507, 0.4366, 0.4225, 0.4085, 0.3944, 0.3803,
        0.3662, 0.3521, 0.3380, 0.3239, 0.3099, 0.2958, 0.2817, 0.2676, 0.2535,
        0.2394, 0.225

In [ ]:
import numpy as np

# 2元素tuple

a = ([1, 2, 3], [4, 5, 6])

# 3x3矩阵H
H = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

# 将2元素tuple转换为numpy数组
a = np.array(a)

# 计算结果
result = np.dot(H, a)

# 打印结果
print(result)


In [2]:
img = 'driver_37_30frame/05181656_0251.MP4/01830.jpg '
img_name = img[:-4]
img_name

'driver_37_30frame/05181656_0251.MP4/01830'